[package]
name = "oddio-engine"
version = "0.1.0"
authors = ["DasEtwas"]
edition = "2018"

[dependencies]
oddio = { git = "https://github.com/Ralith/oddio", rev = "b57a67c307493c79b1467cca8f419a7fad37a27d" }
